config/routes.rb
Rails.application.routes.draw do
  root 'diys#index'

  resources :diys
  resources :users, only: [:index]

  post '/add', to: 'diys#add'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diy.rb
class Diy < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/diys_controller.rb
class DiysController < ApplicationController

  def add
    if cookies[:fav]
      array = cookies[:fav].split('&')
      array << params[:diy_id]
    else
      array = [params[:diy_id]]
    end
    cookies[:fav] = array

    render :text => "OK"
  end

  def index
    @diys = Diy.all.order("id DESC").page(params[:page]).per(9)
    if params[:keyword].present?
      @diys = @diys.where('title LIKE(?)', "%#{params[:keyword]}%")
    end
    if params[:price].present?
      @diys = @diys.where(price: 0..params[:price].to_i)
    end
  end

  def show
    @diy = Diy.find(params[:id])
  end

  def new
    @diy = Diy.new
  end

  def create
  @diy = Diy.new(set_diy)

    if @diy.save
      redirect_to :root
    else
      render :new
    end
  end


  private
  def set_diy
    params.require(:diy).permit(:title, :url, :price, :comment)
  end

end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if cookies[:fav]
      fav = cookies[:fav].split('&')
      @fav = Diy.where(id: fav).order("id DESC").page(params[:page]).per(6)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diys_helper.rb
module DiysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/diys/index.html.haml
.search
  = form_tag('/', :method => :get) do
    .search-keyword
      %p
        Keyword #{text_field_tag 'keyword', ''}
    .search-price
      %p
        Price #{number_field_tag 'price'}
    .search-submit
      = submit_tag "search"
  .result
    - if params[:keyword].present? || params[:price].present?
      %h4 result
      %p
        keyword: #{params[:keyword]}
      %p
        Price: ¥#{params[:price]}　以内
- @diys.each do |diy|
  = link_to diy do
    .diy-card.col-md-3.col-md-4
      .diy-img
        = image_tag(diy.url) if diy.url.present?
      .diy-title
        = diy.title
      .diy-price
        %p
          ¥#{diy.price}
= paginate(@diys)

app/views/diys/new.html.haml
= form_for(@diy, multiple: true) do |f|
  .diy-form
    .diy-card-form
      %h2 Posting
      .diy-title-form
        = f.text_field :title ,placeholder: :title
      .diy-img-form
        = f.text_field :url ,placeholder: :image
      .diy-price-form
        = f.text_field :price, placeholder: :price
      .diy-comment-form
        = f.text_area :comment, placeholder: :comment
      %div
        = f.submit('SEND')

app/views/diys/show.html.haml
.diy-detail-card.col-md-3.col-md-4
  .favorite
    %input#fav{:type => "button", :value => "♡", data: {id: params[:id]}}
  .diy-detail-img
    = image_tag(@diy.url) if @diy.url.present?
  .diy-detail-title
    %h3 Title
    %p= @diy.title
  .diy-detail-price
    %h3 Price
    %p
      ¥#{@diy.price}
  .diy-detail-comment
    %h3 Comment
    %p= @diy.comment

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title DiyCommunity
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %header
      = link_to 'D I Y search', root_path, class: 'logo'
      = link_to 'My Page', users_path, class: 'mypage'
      = link_to 'New DIY', new_diy_path, class: 'new-diy'
    .container
      = yield

app/views/users/index.html.haml
#mypage
  %h3
    %span> ♥
    My Favorite List
    %span{:style => "margin-left:10px;"} ♥
  - if @fav
    - @fav.each do |diy|
      = link_to diy do
        .diy-card.col-md-3.col-md-4
          .diy-img
            = image_tag(diy.url) if diy.url.present?
          .diy-title
            = diy.title
          .diy-price
            %p
              ¥#{diy.price}
  - if @fav
    = paginate(@fav)